"""words table

Revision ID: 5bcd9acd6103
Revises: 20b64ba03db4
Create Date: 2021-10-24 23:24:01.660943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bcd9acd6103'
down_revision = '20b64ba03db4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('part_of_speech',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form', sa.String(length=20), nullable=True),
    sa.Column('pos', sa.String(length=20), nullable=True),
    sa.Column('counting', sa.String(length=20), nullable=True),
    sa.Column('word_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('definition_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sense', sa.String(length=20), nullable=True),
    sa.Column('pos_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pos_id'], ['part_of_speech.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('definition_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phrase_title', sa.String(length=30), nullable=True),
    sa.Column('counting', sa.String(length=20), nullable=True),
    sa.Column('variant_name', sa.String(length=20), nullable=True),
    sa.Column('label', sa.String(length=20), nullable=True),
    sa.Column('english_definition', sa.String(length=150), nullable=True),
    sa.Column('chinese_definition', sa.String(length=50), nullable=True),
    sa.Column('definition_set_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['definition_set_id'], ['definition_set.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('definition_unit')
    op.drop_table('definition_set')
    op.drop_table('part_of_speech')
    # ### end Alembic commands ###
