"""empty message

Revision ID: 6f95b324d862
Revises: db583e484a79
Create Date: 2021-12-22 23:12:36.367905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f95b324d862'
down_revision = 'db583e484a79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pronunciation_region')
    op.drop_table('pronunciation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pronunciation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=20), nullable=True),
    sa.Column('pos_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['pos_id'], ['part_of_speech.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pronunciation_region',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=20), nullable=True),
    sa.Column('pos_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['pos_id'], ['part_of_speech.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
