"""empty message

Revision ID: 8c4dfbbf0c3d
Revises: 5bcd9acd6103
Create Date: 2021-11-10 00:02:05.593964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c4dfbbf0c3d'
down_revision = '5bcd9acd6103'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pronunciation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=20), nullable=True),
    sa.Column('pos_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pos_id'], ['part_of_speech.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pronunciation_region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=20), nullable=True),
    sa.Column('pos_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pos_id'], ['part_of_speech.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pronunciation_region')
    op.drop_table('pronunciation')
    # ### end Alembic commands ###
